language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "zapdos-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: zapdos-shoes
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: QYpAx3xmLylTyiCUrw2XYFn2asO0efBsYTMQA/HePtcNrJwDPXy168tZPF4a08tfzVqxd1KP68lUpbYs+P/6ZiqamGlKkEMrbZB6DIYuI0sHGTXOti5FoKjiwiF3RXjnnFmRvnZy7Db42WYiVGkh4C6brL2o8jj1nO3RXM1z0lW29glTCm3K4HnOYGiP2C9ZjeDBV8/j5Qd0c3IWxel2keCBFkJsvqSlkz1N9jJHR4kGlJAdPntYweV8DICQCbGhrQwcEqfJhpu59PT+2+L9cq2Tp+vhD/InhioabKJYYqrMBWEe77j/rGe43hfcNbnBYqxRJ6mEE37FnYj8NwYqGtFzYUA7dpJutIN9yBuHeFLj0MTEapCZ+RGm46MKZwFT4zYTvCBKuRBRwm0JQc9ESKaN/5FucU/Zi+v/0TlBxs/+6/pys1kyPD/4uib2DKczisxVVSySPmXZ4mh7xdlFHCDYQrH+8/KB1c71FKEQsPiMyIogu+ag8JPEVbVtS3xuGQzDp/3+s10oCi8MyzEVu2lGFwHbRkYPQ+8clS948rNtz98Eh1FJOzItu0q1jsDXpRs03RasoC0NHHxzBRlAQwvrdjHzB4RgNv3MrTlVP95XfguBs3HxoLEyeaeje5tRvc7oczeN3KltI1S9fTcQSXWiJ7i1AJHONwAZHsPwPWY=
